[project]
name = "horde-openai-proxy"
version = "0.1.0"
description = ""
authors = [{ name = "Luke100000", email = "jonas.peche@aon.at" }]
requires-python = ">=3.13,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "cachetools",
    "transformers",
    "sentencepiece",
    "protobuf",
    "jinja2",
    "python-dotenv",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ruff",
    "pre-commit",
    "pytest",
    "requests-mock>=1.12.1",
]
fastapi = ["uvicorn", "fastapi[standard]"]
bridge = ["openai"]

[tool.uv]
default-groups = ["dev"]

[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"
